### ISSUE TITLE
Consistency between consumers

### ISSUE THREAD

**Issue by yann-yinn** [contentacms/contenta_consumers#1]
Today, consumers have a lot of freedom, which is fun, but makes comparison between consumers difficult, or impossible. Should we care about this ? 

Here is the slack message from @bmx269  on contenta channel that raised this point : 

> Here are some things I would like to see for consistency, standardize on:
> - Hosting options (so we can compare apples to apples)
> - URL Structure (Routing)
> - Models used (what data are we showing in the app)
> - API (consume the same API endpoints)
> 
> That is just the start. I think these apps will be used by orgs and customers to determine if the decoupled platform, or a framework is viable. We should allow that, like a todos app, but also be clear as to what is actually similar.

I think hosting is a very valid point, what if firebase is much faster than github pages ? people may think Angular is faster / slower than Vue (just an example)
Same thing if some consumers implements services workers / cache but not the others; etc ...

**Comment by e0ipso** [comment]
I can see value on agreeing on product specifications. However I don't think we should enforce technical solutions. We should, instead, make helper libraries available so consumers can opt-in.

In my opinion the biggest focus should be in **helping lower the barrier of entry of new consumers** instead of making everything consistent to help compare consumer technologies.

While I see the value in helping compare, I think choosing one or the other will always have the biggest factors outside of the tech (company existing projects, integration compatibilities, human resources, hype, …).

Thoughts?

**Comment by joaogarin** [comment]
I totally agree with @e0ipso on this, I dont think we should try to enfore something that in the end might result in strange technical solutions to some communities. Each community has its quirks and choices when it comes to how a specific problem should be solved (sometimes they agree of course but not always) and we should basically develop apps that are easy to jump on and familiar to anyone looking at them comming from that specific community (angular, react, ember, vue etc..).

An example would be to for example have a angular app that uses axios for http (just for the sake of consistency and standardization). that would be odd and unfamiliar to anyone coming to it from the angular community perspective since angular provides its own Http solution out of the box.which 99,9% of angular developers use. its a bit of a ridiculous example but could be applied to other things even like hosting or which theme / component library to use..

I think the choice of what frontend of technology to use will not really be something that our solutions will influence, not at least on the majority of cases. It will be driven like @e0ipso said by mostly external factors..which doesn't mean having a vast choice to pick from is not useful.

**Comment by e0ipso** [comment]
`<offtopic>`
> It will be driven like @e0ipso said by mostly external factors..which doesn't mean having a vast choice to pick from is not useful.

IMO this is exactly why _having a vast choice to pick from_ is extremely useful.
`</offtopic>`

**Comment by dawehner** [comment]
I'm all for collecting recommendations

* Use SEO friendly URLs
* Use your own models, not just copy all the data from the HTTP response
* Maybe use service workers, if possible (Note: A lot of people struggle a LOT with service workers)
* etc. 

These are really valueable pieces of information, but I agree with @e0ipso that we should not try to introduce stricter rules which increase the barrier. Let's make recommendations, but let's treat that rather as recommendations / guidelines people can take into account, when they need ideas how to solve a specific problem.

What do you think about that?

**Comment by yann-yinn** [comment]
> **helping lower the barrier of entry of new consumers**

I agree, contenta_vue_nuxt focus on this objective. I would like the project to be somehow easy to fork and starts with. 

But i guess some people or companies might be very interested in comparing consumers and trying to get some conclusions, because at the end, it will be an awesome showcase. We may or may not care about them ... 

at least it might be interesting to have all project hosting at the same place, because sometimes i wondering if my application is slower / faster because of that .

**Comment by e0ipso** [comment]
Hmm, that's an interesting thought. As I understand different hosting environment may be tuned better to certain technologies. I would assume that there are certain hosting environments that are friendly to all.

@nyl-auster can you help research what can be a hosting environment that meets the following requirement?

  - Serve all our consumers.
  - It's free for us to use.

When we have a hosting environment (probably deserves a separate issue), we should have automatic release deploys to that hosting (another separate issue, per consumer).

The work for each consumer to auto-deploy should be able to be completed by someone outside of the consumer project. Having that auto-deploy does not preclude consumer leads to also deploy to their favorite environment.

Does that sound like a fair first step? Is this an initiative that you'll want to lead, or do you want to wait for someone else to step in?

Anyone, thoughts?

**Comment by yann-yinn** [comment]
Waiting to see what other consumers thinks about that ... 
not a lot of knowledges but i was thinking about "now" ( because it works well with static sites, nodejs or docker in one single command ) : https://zeit.co/ but i didn't check the prices

PS : the idea behind now is to deploy by simply typing "now {your project}"

**Comment by e0ipso** [comment]
@nyl-auster I think we can have someone to figure out the auto deploy when we find a suitable hosting. We may not even need that `now` tool, but it definitely is something we want to explore.

Can you open a separate issue for hosting so we don't sidetrack conversation here?

**Comment by joaogarin** [comment]
> @nyl-auster can you help research what can be a hosting environment that meets the following requirement?
> 
> Serve all our consumers.
> It's free for us to use.

I would add supports server rendering.

I think this might go a bit into the "too strict" thing we where talking about. I totally don't mind having the angular in the same hosting as any other frontend demo if that helps, but I don't truly think this would be a factor for anyone choosing one solution over another. 

One might prefer digital ocean because already has his drupal in there, or might prefer now because its just so simple, or maybe firebase because for ex in angular is just super integrated with everything-google..I wouldn't even expect anyone to check where each frontend is hosted. I have checked elm and vue demos already and have no idea where they are hosted..

**Comment by bmx269** [comment]
I asked the questions, not to cause limitations, but to make it easier for someone to quickly use the details, to help with app structure decisions, making building a consuming app demo faster.

**Comment by yann-yinn** [comment]
@bmx269 right. So my suggestion is to close this issue and feeding the wiki page according to recommendations, so that consumers know how to get started and what they can or can not do : https://github.com/contentacms/contenta_consumers/wiki

Feel free to re-open if needed
