### ISSUE TITLE
Same host for all consumers

### ISSUE THREAD

**Issue by yann-yinn** [contentacms/contenta_consumers#2]
For the "why?", see this issue : https://github.com/contentacms/contenta_consumers/issues/1#issuecomment-314419016

Anyone has an idea of an hosting solution that would fit our needs for all our consumers ?
- free for us
- super cool if it has a nodeJS server ( because _contenta_vue_nuxt_ is also Server Side Rendered )

I was thinking about something like [now](https://zeit.co/now#whats-now) because it supports nodeJS but i guess there might be several solutions out there meeting those requirements. Can firebase do the job for all of us ?

**Comment by joaogarin** [comment]
Picking up on https://github.com/contentacms/contenta_consumers/issues/1#issuecomment-314443183

> @nyl-auster can you help research what can be a hosting environment that meets the following requirement?
> 
> Serve all our consumers.
> It's free for us to use.

I would add supports server rendering.

I think this might go a bit into the "too strict" thing we where talking about. I totally don't mind having the angular in the same hosting as any other frontend demo if that helps, but I don't truly think this would be a factor for anyone choosing one solution over another. 

One might prefer digital ocean because already has his drupal in there, or might prefer now because its just so simple, or maybe firebase because for ex in angular is just super integrated with everything-google..I wouldn't even expect anyone to check where each frontend is hosted. I have checked elm and vue demos already and have no idea where they are hosted..

**Comment by joaogarin** [comment]
> I was thinking about something like now because it supports nodeJS but i guess there might be several solutions out there meeting those requirements. Can firebase do the job for all of us ?

I dont think firebase can do the work for proper server rendering..I dont know maybe they added it already but a while ago it wasnt really there..

**Comment by yann-yinn** [comment]
@joaogarin hi ! we should rather discuss about this (should we do something or not) on the other issue if you don't mind : https://github.com/contentacms/contenta_consumers/issues/1

**Comment by yann-yinn** [comment]
@joaogarin do you know any cool host solution with free nodeJS support ? At least i need to move my own site to another host, it gives me extra work to make Nuxt.js works on github pages ( or some dynamic pages will NOT be rendered, which is not the point of using Nuxt :-p )

**Comment by joaogarin** [comment]
@nyl-auster I will copy my first response to that issue. regarind : 

> @joaogarin do you know any cool host solution with free nodeJS support ? At least i need to move my own site to another host, it gives me extra work to make Nuxt.js works on github pages

Have you tried https://www.heroku.com/? Deployment is crazy simple there.. I think now is also a very good solution from what it seems. never tried it though. I would say that we the question here is server rendering. so I think firebase might not be a good option. But lets let the other guys throw their suggestions here.

I would say though that would need to be one of these "plug and play" hosting solutions..that although they might not provide the best performance (since we will not be paying) they are quick, simple and in the end get the job done for showing some sample apps.

**Comment by justafish** [comment]
There's is going to be negligible differences between hosting JavaScript on GH pages, Firebase, Heroku etc. I think it's better to let the consumer maintainer decide where they want to host/deploy from.

I'm using Heroku for the React app, but I don't think it's a good fit for every consumer, it depends on the implementation and it's requirements, so I don't think this is practical to enforce

**Comment by bmx269** [comment]
Heroku is good if you need Node.js and SSR, which is something Ember, Vue, React, and others supports.

**Comment by yann-yinn** [comment]
conclusion of https://github.com/contentacms/contenta_consumers/issues?q=is%3Aissue+is%3Aclosed is that consumers should remain free to implement things in the way they want, we are just giving recommandations : https://github.com/contentacms/contenta_consumers/wiki

I m going to add "Heroku" and "now" as nice options for consumers needing NodeJS support.

**Comment by yann-yinn** [comment]
So i close this issue to, feel free to re-open is needed
